server:
  port: 8808
  servlet:
    context-path: /demo
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo1212?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

